name: jobcrawler
on:
  schedule:
    - cron: '0 11,23 * * *' # at 6 AM and 6 PM UTC+7
  workflow_dispatch:

jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GHPAT }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install dependency
        run: sudo apt install libcurl4-openssl-dev libgit2-dev
        
      - name: Install R packages
        run: | 
          R -q -e 'install.packages(c("dplyr", "httr", "RSelenium", "jsonlite", "rvest", "stringr", "telegram.bot", "tidyr", "purrr", "glue", "genTS", "strex", "readr", "netstat"), dependencies = TRUE)'
          
      - name: Run crawler and forwarder script
        run: | 
          Rscript scrape_send_linkedin.R
        
      - name: Set today
        id: set_today
        run: echo "::set-output name=today::$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')"  
        
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Updated: ${{ steps.set_today.outputs.today }}" || exit 0
          git push
